src/Entity/Consultation.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ConsultationRepository")
 * @UniqueEntity(fields="date", message="Vous avez déja validé cette consultation")
 */
class Consultation
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime", unique=true)
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez indiquer un diagnostic")
     */
    private $diagnostic;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="veuillez indiquer un traitement")
     */
    private $traitement;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez saisir un commentaire")
     */
    private $commentaire;
    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez selectionner un type de paiement")
     */
    private $paiement;

    /**
     * @var Booking
     * @ORM\OneToOne(targetEntity="App\Entity\Booking", inversedBy="consultation", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $booking;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getDiagnostic(): ?string
    {
        return $this->diagnostic;
    }

    public function setDiagnostic(string $diagnostic): self
    {
        $this->diagnostic = $diagnostic;

        return $this;
    }

    public function getTraitement(): ?string
    {
        return $this->traitement;
    }

    public function setTraitement(string $traitement): self
    {
        $this->traitement = $traitement;

        return $this;
    }

    public function getCommentaire(): ?string
    {
        return $this->commentaire;
    }

    public function setCommentaire(string $commentaire): self
    {
        $this->commentaire = $commentaire;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getPaiement()
    {
        return $this->paiement;
    }

    /**
     * @param mixed $paiement
     * @return Consultation
     */
    public function setPaiement($paiement)
    {
        $this->paiement = $paiement;
        return $this;
    }

    public function getBooking(): ?Booking
    {
        return $this->booking;
    }

    public function setBooking(Booking $booking): self
    {
        $this->booking = $booking;

        return $this;
    }

    public function getUser()
    {
        return $this->booking->getUser();
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}PROJET JACL{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        {% block stylesheets %}
            <link rel="stylesheet" href="{{ asset('lib/bootstrap.min.css') }}">
            <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/flick/jquery-ui.css">
            <link rel="stylesheet" href="{{ asset('style/style.css') }}">
            <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
            <link rel="stylesheet" href="{{ asset('style/style.css') }}">
            <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
        {% endblock %}
    </head>
    <body >
        {% if is_granted('ROLE_ADMIN') %}

            <nav class=" navbar-dark navbar-expand-md  myAdminNav">
                <div class="container navbar-nav ">
                    <a class="navbar-brand text-center text-uppercase" href="{{ path('app_index_index') }}">dashboard</a>
                    <div class="navbar-collapse ml-3 ">
                        <ul class="navbar-nav  ">
                            <li class="nav-item">
                                <a class="nav-link " href="{{ path('app_admin_admin_index') }}">Gestion des Séances</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ path('app_admin_admin_allmypatients') }}">Mes Patients</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ path('app_admin_admin_historiqueconsultation')
                                }}">Historique des Consultations</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        {% endif %}
            <!--LEFT PART-->
            <nav class="navbar navbar-expand-md navbar-light bg-transparent ">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <div class="d-none d-sm-block">
                            <a class="navbar-brand" href="{{ path('app_index_index') }}"><img  src="{{ asset('images/logo-crack.png') }}" height="50px" alt="logoSite"></a>
                        </div>
                        <li class="nav-item  align-self-center">
                            <a class="nav-link bordure" href="{{ path('app_index_index') }}">Accueil<span class="sr-only">
                                    (current)</span></a>
                        </li>
                        {% if app.user is not null %}
                        <li class="nav-item  align-self-center">
                            <a class="nav-link bordure" href="{{ path('app_booking_takemyrdv') }}">Rendez-Vous</a>
                        </li>
                            {% else %}
                                <li class="nav-item align-self-center">
                                    <a class="nav-link bordure" href="{{ path('app_security_login') }}">Rendez-Vous</a>
                                </li>
                        {% endif %}
                        <li class="nav-item align-self-center">
                            <a class="nav-link bordure" href="{{ path('app_index_apropos') }}">A Propos</a>
                        </li>
                        <li class="nav-item align-self-center">
                            <a class="nav-link bordure" href={{ path('app_index_nospatients') }}>Nos patients</a>
                        </li>
                        <li class="nav-item align-self-center">
                            <a class="nav-link bordure" href={{ path('app_index_contact') }}>Contact</a>
                        </li>
                    </ul>
                </div>
                <div>

                    <nav class="navbar navbar-expand navbar-light bg-transparent  ">
                        <div class="collapse navbar-collapse" id="navbarNav">
                            <ul class="navbar-nav">
                        {% if app.user is null%}
                            <li class="nav-item">
                                <button class="btn btn-primary sign p-0 mr-4"><a class="nav-link text-light" href="{{ path('app_security_register')}}">Inscription</a></button>
                            </li>
                            <li class="nav-item">
                                <button class="btn btn-outline-success sign p-0"><a class="nav-link text-success" href="{{ path('app_security_login') }}">Connexion</a></button>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a href="{{ path('app_user_index') }}" class=" nav-link">
                                    {% if app.user.sexe == 'm' %}
                                        <img class="mr-1" style="height:40px;" src="{{ asset('images/man.png') }}">
                                    {% elseif app.user.sexe == 'f' %}
                                        <img class="mr-1" style="height:40px;" src="{{ asset('images/girl.png') }}">
                                    {% endif %}
                                    {{ app.user }}
                                </a>
                            </li>
                            <li class="nav-item align-self-center">
                                <button class="btn btn-danger align-self-center sign p-0"><a class="nav-link text-white" href="{{ path('app_security_logout') }}" >Déconnexion</a></button>
                            </li>
                        {% endif %}
                            </ul>
                        </div>
                    </nav>
                </div>


            </nav>



        <div class="container">
            {# affichage des messages flash #}
            {% for type, flashes in app.session.flashBag.all %}
                {% for message in flashes %}
                    {# pour la classe alert-danger du bootstrap #}
                    {% if type == 'error' %}
                        {% set type = 'danger' %}
                    {% endif %}
                    <div class=" mt-3 alert alert-{{ type }}">
                        {{ message|raw }}
                    </div>
                {% endfor %}
            {% endfor %}
        </div>



            {% block body %}

            {% endblock %}
        <div id="footer">
        <footer class="footer footer-block">
            <div class="container-fluid text-light bg-dark py-3 mt-3">
                <div class="row">

                    <div class="col-12 col-md-6 text-center text-md-left">
                        <div class="text-uppercase pl-0 pl-md-5">nos partenaires</div>
                        <div>
                            <a href="https://www.chiropraxie.com" target="_blank">
                                <img src="{{ asset('images/logo-afc.png') }}" alt="lien vers association française de chiropraxie" height="70px" class="pl-0 pl-md-5">
                            </a>
                        </div>
                    </div>


                    <div class="col-12 col-md-6 copy-footer align-self-md-end text-md-right text-center">
                        <span>Copyright &copy 2019 Projet Webforce3 Tous droits réservés</span>
                    </div>

                </div>
            </div>
        </footer>
        </div>

            {% block javascripts %}

                <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
                <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
                <script src="{{ asset('lib/bootstrap.min.js') }}" ></script>
                <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>
                <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
                <script type="text/javascript" src="{{ asset('script/jquery-ui-timepicker-addon.js') }}"></script>
                <script src="{{ asset('script/jquery-ui-timepicker-fr.js') }}"></script>
                <script>
                    /*var d = new Date();
                    var n = d.getHours();*/
                     var disableddates = [["01","01"], ["01","05"], ["08","05"], ["14","07"], ["15","08"], ["11","11"], ["01","11"], ["25","12"], ["31","12"]];


                    function nationalDays(date) {
                        for (i = 0; i < disableddates.length; i++) {
                            if (date.getMonth() == disableddates[i][1] - 1 && date.getDate() == disableddates[i][0]) {
                                return [false, ''];
                            }
                        } return [true, ''];
                    }

                    function noWeekendsOrHolidays(date) { var noWeekend = $.datepicker.noWeekends(date); if (noWeekend[0]) { return nationalDays(date); } else { return noWeekend; } }


                    $('.datepicker').datetimepicker({
                        minDate: 1,
                        hourMin: 9,
                        hourMax: 18,
                        firstDay: 1,
                        beforeShowDay: noWeekendsOrHolidays

                    });
                </script>
                {#}<script>$('.datepicker').datetimepicker();</script>{#}
            {% endblock %}
        </body>

</html>