src/Entity/Booking.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 * @UniqueEntity(fields="date", message="Cet horaire est déjà reservé")
 */
class Booking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="datetime", unique=true)
     * @Assert\NotBlank(message="La date du RDV n'est pas renseignée")
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez selectionner un motif de consultation")
     */
    private $motive;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank(message="Veuillez renseigner votre profession")
     */
    private $job;

    /**
     * @ORM\Column(type="string", length=3)
     * @Assert\NotBlank(message="Ce champs est obligatoire")
     */
    private $smoker;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotBlank(message="ce champs est obligatoire")
     */
    private $medical_past;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\NotBlank(message="ce champs est obligatoire")
     */
    private $sports;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="ce champs est obligatoire")
     */
    private $medication;

    /**
     *
     * @ORM\Column(type="string", length=50)
     * @Assert\NotBlank(message="ce champs est obligatoire")
     */
    private $allergies;

    /**
     * @ORM\Column(type="integer", length=2)
     * @Assert\NotBlank(message="Ce champs est obligatoire")
     */
    private $sleep_schedule;

    /**
     * @ORM\Column(type="string", length=25)
     *
     */
    private $status = 'EN_ATTENTE';

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Consultation", mappedBy="booking", cascade={"persist", "remove"})
     */
    private $consultation;


    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @return mixed
     */
    public function getAllergies(): ?string
    {
        return $this->allergies;
    }

    /**
     * @param mixed $allergies
     * @return Booking
     */
    public function setAllergies(string $allergies):self
    {
        $this->allergies = $allergies;
        return $this;
    }


    /**
     * @param mixed $user
     * @return Booking
     */
    public function setUser($user)
    {
        $this->user = $user;
        return $this;
    }


    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getMotive(): ?string
    {
        return $this->motive;
    }

    public function setMotive(string $motive): self
    {
        $this->motive = $motive;

        return $this;
    }

    public function getJob(): ?string
    {
        return $this->job;
    }

    public function setJob(string $job): self
    {
        $this->job = $job;

        return $this;
    }

    public function getSmoker(): ?string
    {
        return $this->smoker;
    }

    public function setSmoker(string $smoker): self
    {
        $this->smoker = $smoker;

        return $this;
    }

    public function getMedicalPast(): ?string
    {
        return $this->medical_past;
    }

    public function setMedicalPast(string $medical_past): self
    {
        $this->medical_past = $medical_past;

        return $this;
    }

    public function getSports(): ?string
    {
        return $this->sports;
    }

    public function setSports(string $sports): self
    {
        $this->sports = $sports;

        return $this;
    }

    public function getMedication(): ?string
    {
        return $this->medication;
    }

    public function setMedication(string $medication): self
    {
        $this->medication = $medication;

        return $this;
    }

    public function getSleepSchedule(): ?int
    {
        return $this->sleep_schedule;
    }

    public function setSleepSchedule(int $sleep_schedule): self
    {
        $this->sleep_schedule = $sleep_schedule;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * @param mixed $status
     * @return Booking
     */
    public function setStatus($status)
    {
        $this->status = $status;
        return $this;
    }

    public function getConsultation(): ?Consultation
    {
        return $this->consultation;
    }

    public function setConsultation(Consultation $consultation): self
    {
        $this->consultation = $consultation;

        // set the owning side of the relation if necessary
        if ($this !== $consultation->getBooking()) {
            $consultation->setBooking($this);
        }

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Doctrine\DBAL\Types\IntegerType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'lastname',
                TextType::class,
                [
                    'label' => 'Nom :'
                ]
            )
            ->add(
                'firstname',
                TextType::class,
                [
                    'label' => 'Prénom :'
                ]
            )
            ->add(
                'age',
                TextType::class,
                [
                    'label' => 'Age :'
                ]
            )
            ->add(
                'email',
                EmailType::class,
                [
                    'label' => 'Email'
                ]
            )
            ->add(
                'sexe',
                ChoiceType::class,
                [
                    'choices' => [
                        'Homme' => 'm',
                        'Femme' => 'f'
                    ],
                    'expanded' => true

                ]
            )
            ->add(
                'telephone',
                TextType::class,
                [
                    'label' => 'Téléphone (fixe ou portable) :',
                    'attr' => array(
                        'placeholder' => 'exemple : 0102030405'
                    )
                ]
                )
            ->add(
                'plainPassword',
                // 2 champs qui doivent avoir la meme valeur
                RepeatedType::class,
                [
                    // ... de type password
                    'type' => PasswordType::class,
                    // options du 1er champs
                    'first_options' => [
                        'label' => 'Mot de passe :'
                    ],
                    // options du 2eme champs
                    'second_options' => [
                        'label' => 'Confirmation du mot de passe :'
                    ],
                    // message si les 2 champs n'ont pas la meme valeur
                    'invalid_message' => 'La confirmation ne correspond pas au mot de passe'
                ]
            )
            ->add('adress',
                TextType::class,
                [
                    'label' => 'Adresse postale :'
                ]
                )
            ->add('city',
                TextType::class,
                [
                    'label' => 'Ville :'
                ]
            )
            ->add('zipcode',
                TextType::class,
                [
                    'label' => 'Code postal :'
                ]
                )
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
            'validation_groups' => ['create']
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\Booking;
use App\Entity\User;
use App\Form\UserEditType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class UserController extends AbstractController
{
    /**
     * @Route("/utilisateur")
     */
    public function index()
    {
        $em = $this->getDoctrine()->getManager();
        $user = $this->getUser();
        $repositoryBookings = $em->getRepository(Booking::class);

        $appointments = $repositoryBookings->findBy(
            [
                'user' => $user->getId(),
                'status' => 'EN_ATTENTE'
            ],
            ['date' => 'ASC']);


        return $this->render('user/index.html.twig',
            [
                'profile' => $user,
                'appointments' => $appointments
            ]
        );
    }

    /**
     * @Route("/utilisateur/modification")
     */
    public function edit(Request $request, UserPasswordEncoderInterface $passwordEncoder)
    {
        $em = $this->getDoctrine()->getManager();
        /** @var User $user */
        $user = $this->getUser();

        $form = $this->createForm(UserEditType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            if ($form->isValid()) {

                if (!empty($user->getPlainPassword())) {
                    $password = $passwordEncoder->encodePassword($user, $user->getPlainPassword());
                    $user->setPassword($password);
                }


                $em->persist($user);
                $em->flush();

                // message de confirmation
                $this->addFlash('success', "La modification est enregistrée");
            } else {
                $this->addFlash('error', 'Le formulaire contient des erreurs');
            }
        }

        return $this->render('user/edit.html.twig',
            [
                'form' => $form->createView()
            ]
        );
    }
}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ app.user }} - Projet JACL{% endblock %}

{% block body %}
    <div class="container">
        <h1>Modification du profil</h1>

        {{ form_start(form) }}
            {{ form_row(form.firstname) }}
            {{ form_row(form.lastname) }}
            {{ form_row(form.age) }}
            {{ form_row(form.email) }}
            {{ form_row(form.telephone) }}
            {{ form_row(form.adress) }}
            {{ form_row(form.city) }}
            {{ form_row(form.zipcode) }}
            {{ form_row(form.plainPassword) }}
            <button type="submit" class="btn btn-info">Modifier</button>
            <button class="btn btn-info"><a class="text-white text-decoration-none" href="{{ path('app_user_index') }}">Retour</a> </button>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ app.user }} - Projet JACL{% endblock %}

{% block body %}
    <div class="container">

        <div class="col-md-12 d-flex justify-content-center mt-4 mb-2">
                <div class=" col-10 col-md-4 card shadow  text-black-50 p-0 " >
                    <div class="card-header text-black-50 font-weight-bold text-center">
                        <h3>Mon Profil</h3>
                    </div>
                    <div class="card-body p-0">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item text-black-50"><strong>Nom</strong> : {{ profile.lastname }}</li>
                            <li class="list-group-item text-black-50"><strong>Prénom</strong> : {{ profile.firstname }}</li>
                            <li class="list-group-item text-black-50"><strong>Age</strong> : {{ profile.age }}</li>
                            <li class="list-group-item text-black-50"><strong>Email</strong> : {{ profile.email }}</li>
                            <li class="list-group-item text-black-50"><strong>Adresse</strong> : {{ profile.adress }}</li>
                            <li class="list-group-item text-black-50"><strong>Ville</strong> : {{ profile.city }}</li>
                            <li class="list-group-item text-black-50"><strong>Code postal</strong> : {{ profile.zipcode }}</li>
                            <li class="list-group-item text-black-50"><strong>Téléphone</strong> : {{ profile.telephone }}</li>
                        </ul>

                    </div><!-- FIN CARD BODY-->

                </div><!--FIN CARD -->

            </div><!--Fin col-md-12-->

        <div class="col-12 d-flex justify-content-center mb-2 mb-md-4" >
            <a href="{{ path('app_user_edit') }}" class="btn btn-outline-info">Modifier</a>
            <a href="{{ path('app_index_index') }}" class="btn btn-outline-info ml-2">Retour Accueil</a>
        </div>


            <h3 class="text-uppercase text-center myTitleSeance">Mes rendez-vous</h3>
        

        <div class="row justify-content-around">

        {% for appointment in appointments %}


            <div class="card mt-4 text-black-50 col-10 col-md-3 d-md-flex d-block p-0 ml-4 ml-md-0"  >
                <div class="card-body p-0">
                    <div class="card-header text-center font-weight-bold"  >
                        {{ appointment.date|date("d/m/Y H:i") }}
                    </div>
                    <div class="p-3">
                        <p class="card-text"><strong>Antécédents :</strong> {{ appointment.medicalPast }}</p>
                        <p class="card-text"><strong>Allergies :</strong> {{ appointment.allergies }}</p>
                        <p class="card-text"><strong>Profession :</strong> {{ appointment.job }}</p>
                        <p class="card-text"><strong>Médication :</strong> {{ appointment.medication }}</p>
                        <p class="card-text"><strong>Motif de rendez-vous :</strong> {{ appointment.motive }}</p>
                        <p class="card-text"><strong>Fumeur :</strong> {{ appointment.smoker }}</p>
                        <p class="card-text"><strong>Pratique du sport :</strong> {{ appointment.sports }}</p>
                    </div>
                </div>
            </div>
            {% else %}
                <h3 class="text-center">Aucun rendez-vous de prévu</h3>


            {% endfor %}

    </div>
</div><!-- FIN container-->

{% endblock %}